### ISSUE TITLE
Import from google drive fails

### ISSUE THREAD

**Issue by TimeScience** [AuScalableDroneCloud/Tracker#42] opened 2023-03-21 04:51 UTC
Google drive import fails. Error below is on dev. On production branch it seems to just hang at 0% uploaded

![image](https://user-images.githubusercontent.com/3067588/226519201-1d40d04e-8fc2-4028-8cfb-1ea99b0bef2b.png)

**Comment by OKaluza** [comment] 2023-03-21 04:53
Duplicate of #41

**Closed by OKaluza** 2023-03-21 04:53 UTC
