### ISSUE TITLE
Can't duplicate tasks

### ISSUE THREAD

**Issue by TimeScience** [AuScalableDroneCloud/Tracker#26] opened 2023-01-18 21:50 UTC
Task duplication often fails or if it works, source images aren't actually duplicated so task can't be re-run.
Generally, the output data duplicated, but most often the source images aren't duplicated

See for example this duplicate task which I am unable to duplicate
project ID =52
Original task that can't eb duplicated: 4f3a6cb0-6b47-4dfc-9d10-fb84076245b3
Duplicated Task with ouptut data but no original images = cc2519ee-1c5f-4aa1-9cec-6295f70faf45

**Comment by OKaluza** [comment] 2023-03-03 02:13
Closing issue as duplicate of #25 if this is still occurring on dev, or after next production rollout please reopen.

**Closed by OKaluza** 2023-03-03 02:13 UTC
